# Data Cleaning & Preparation Steps
### Cleaning process 
1. Check for Missing Values
2. Check for Duplicates
3. Validate Column Names
4. Check Data Types
5. Check for Outliers

### Adding process 
1. Add Wine Type Column so that the two sources can be one

#### Loade data

In [3]:
import pandas as pd

In [4]:
def load_xls_data(filepath):
    df = pd.read_excel(filepath, header = 1) ## removing the first column
    return df

In [5]:
white_data = load_xls_data(r"C:\Users\rebec\OneDrive\Dokumenter\CPH.buisness\4_Semester\BI\all_MiniProjects\MiniProject_group15\MiniProject_2\data\winequality-white.xlsx")

In [6]:
white_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

### Cleaning process

In [7]:
## Check for missing values
white_data.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [8]:
## Check for duplicates 
white_data.duplicated().sum()

937

In [9]:
## Dropping the duplicates rows and saving the data in a new variable: new_white_data
new_white_data =  white_data.drop_duplicates()

In [10]:
## Validate Column Names - Making sure column names are consistent:

# Remove extra space , lowercase & Underscore instead of spaces
new_white_data.columns = new_white_data.columns.str.strip().str.lower().str.replace(' ', '_')

print(new_white_data.columns)

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'ph', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [11]:
## Check Data Types
new_white_data.dtypes

fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
ph                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [12]:
## Check for Outliers
new_white_data.describe()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,ph,sulphates,alcohol,quality
count,3961.000000,3961.000000,3961.000000,3961.000000,3961.000000,3961.000000,3961.000000,3961.000000,3961.000000,3961.000000,3961.000000,3961.000000
mean,6.839346,0.280538,0.334332,5.914819,0.045905,34.889169,137.193512,0.993790,3.195458,0.490351,10.589358,5.854835
std,0.866860,0.103437,0.122446,4.861646,0.023103,17.210021,43.129065,0.002905,0.151546,0.113523,1.217076,0.890683
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.600000,0.035000,23.000000,106.000000,0.991620,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,4.700000,0.042000,33.000000,133.000000,0.993500,3.180000,0.480000,10.400000,6.000000
75%,7.300000,0.330000,0.390000,8.900000,0.050000,45.000000,166.000000,0.995710,3.290000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

Based on the describtion, there are several outliers
1. residual_sugar	
2. chlorides
3. free_sulfur_dioxide
4. total_sulfur_dioxide
5. volatile_acidity
6. citric_acid
7. density

In [13]:
## Outlier example: residuall_sugar  
print(new_white_data['residual_sugar'].describe())
## Most wines have sugar levels between 1.6 and 8.9. But 65.8 is  outside this range

count    3961.000000
mean        5.914819
std         4.861646
min         0.600000
25%         1.600000
50%         4.700000
75%         8.900000
max        65.800000
Name: residual_sugar, dtype: float64

### Adding process

In [20]:
## Add Wine Type Column
white_wine_type = new_white_data.copy()

white_wine_type['wine_type'] = 'white'

print(white_wine_type.columns)

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'ph', 'sulphates', 'alcohol', 'quality', 'wine_type'],
      dtype='object')

In [22]:
# Saving the cleaned data sheet as a csv file.

white_wine_type.to_csv('white_wine_cleaned.csv', index=False)

In [26]:
df1 = pd.read_csv("red_wine_cleaned.csv", header =0)
df2 = pd.read_csv("white_wine_cleaned.csv", header =0)

In [35]:
df = pd.concat([df1,df2], ignore_index=True)

In [36]:
df.to_csv("red_white_wine_cleaned.csv")